name: 1-day-mixpanel-orgtype-sync
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - name: Call dev api/development/identify-by-domain
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          URL: '${{ secrets.DEV_API_URL }}/api/development/identify-by-domain'
        run: |
          curl --request POST \
          --url $URL \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'

      - name: Call prod api/development/identify-by-domain
        if: ${{ github.ref == 'refs/heads/prodenv' }}
        env:
          URL: '${{ secrets.PROD_API_URL }}/api/development/identify-by-domain'
        run: |
          curl --request POST \
          --url $URL \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: echo value
        run: echo 'Hello world. This is running'
