name: 1-day-mixpanel-orgtype-sync
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - name: Call dev api/development/identify-by-domain
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          curl --request GET \
          --url $URL \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
        env:
          URL: ${{ format('{0}/{1}', secrets.DEV_API_URL, '/api/development/identify-by-domain') }}
      - name: Call prod api/development/identify-by-domain
        if: ${{ github.ref == 'refs/heads/prodenv' }}
        run: |
          curl --request GET \
          --url $URL \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
        env:
          URL: ${{ format('{0}/{1}', secrets.PROD_API_URL, '/api/development/identify-by-domain') }}
      - name: echo value
        run: echo 'Hello world. This is running'
